POST http://localhost:8080/medicines/create
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJteXVzZXIiLCJleHAiOjE2MjY1ODQ5NTMsImlhdCI6MTYyNjU2Njk1M30.hyVsDMb8SVt85xAhCY62uARHUBK2BwHTi6DeuAu7HKDGFtYuVX40KFSUmR1LjKswdabop1niltwStv2ZsUo3ag

pzn=123&friendlyName=name&medicineForm=PILL&amount=2&username=myuser2



###
POST http://localhost:8080/users/create
Content-Type: application/x-www-form-urlencoded

username=myuser2&password=mypass&email=gil@hro.de&isPharmacist=true&addressStreet=mystreet&addressHouseNumber=42&addressPostcode=12345


###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "myuser",
  "password": "mypass"
}




