GET http://localhost:8080/users/index
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWwyIiwiZXhwIjoxNjMyODg1Mzc3LCJpYXQiOjE2MzI4NjczNzd9.WLW-IyHWdG8FVledYjXhVE5sCOplS7U1lSkVu678fkZOKTgaLtvxbDyT_k81wllCTUg83MFV7waeao46mEJhug

###
POST http://localhost:8080/medicines/create
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWwyIiwiZXhwIjoxNjMyODg1Mzc3LCJpYXQiOjE2MzI4NjczNzd9.WLW-IyHWdG8FVledYjXhVE5sCOplS7U1lSkVu678fkZOKTgaLtvxbDyT_k81wllCTUg83MFV7waeao46mEJhug

pzn=126&friendlyName=name&medicineForm=PILL&amount=3&username=gil2

###
GET http://localhost:8080/medicines/index?username=gil2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWwyIiwiZXhwIjoxNjMyODg1OTE3LCJpYXQiOjE2MzI4Njc5MTd9.0UKUAyYePITh1MkvZJ5npZUR3lajnp7sIiWTei0uqsM5CfQjyrgxDawDNO8HQA0_qEICCh-yJGljdfCDFhxJPQ
Accept: application/json


###
POST http://localhost:8080/users/create
Content-Type: application/x-www-form-urlencoded

username=gil2&password=mypass&email=cphconrad@gmail.com&isPharmacist=true&addressStreet=mystreet&addressHouseNumber=42&addressPostcode=12345


###
DELETE http://localhost:8080/users/delete
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWwyIiwiZXhwIjoxNjMyODg1Njc4LCJpYXQiOjE2MzI4Njc2Nzh9.G6HYMGIWAsIngfMp-edVO2YU3z0xcqVL3TTOE4zRjNXUGXNEyBOW5vXUb1Aeg_5VfuJGtCcqKsR-RN3ptbsUSQ

username=gil2

###
PUT http://localhost:8080/users/update
Content-Type: application/x-www-form-urlencoded
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaWwiLCJleHAiOjE2MzEwMzYyOTIsImlhdCI6MTYzMTAxODI5Mn0.rJyK421fRFkv6VR3FPGxR_32PpXb_eglmOljbrd1l-6qOzdD8UWbKUHlVBEVRGWUjVQfkkXycQHqj3bywX2spw

username=gil2&password=mypass&email=cphconrad@gmail.com&isPharmacist=true&addressStreet=mystreet&addressHouseNumber=42&addressPostcode=12345

###
POST http://localhost:8080/users/passwordReset
Content-Type: application/x-www-form-urlencoded

username=myuser8&newPassword=hrododoc12


###
GET http://localhost:8080/registrationConfirm?token=89b20781-564c-47d6-a272-646e79a29520
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "gil2",
  "password": "mypass"
}

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "Dennis_Ritchie",
  "password": "pass1235"
}


###
PUT http://localhost:8080/users/ban
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEZW5uaXNfUml0Y2hpZSIsImV4cCI6MTYzMDg2Mzk3MSwiaWF0IjoxNjMwODQ1OTcxfQ.oInQ2g6pldVuj5MWIqy_r9q71Agr_KcoUh0VFCtt0j2sd90HSBqN15JdYZgYkKIhEkETEsKDgvCb-NGEnEQZ5Q

username=myuser4


###
POST http://localhost:8080/admin/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJteXVzZXI4IiwiZXhwIjoxNjI5NTg2NjkyLCJpYXQiOjE2Mjk1Njg2OTJ9.Vxldg5Ua4WDh8SCvZF778IduSTOqwRuqLXBBPFVhB0CYUCCKy0EJeuZNGcqPjQg9jmmLcRbs-uuRbB3yX4mi4w





